import { Flight, ParsedSearchParams, CabinClass, Currency } from './types';

interface AirportMeta {
  fullName: string;
  city: string;
  country: string;
}

const AIRPORT_DIRECTORY: Record<string, AirportMeta> = {
  // Russia & CIS
  MOW: { fullName: 'Москва (Шереметьево)', city: 'Москва', country: 'Россия' },
  SVO: { fullName: 'Москва (Шереметьево)', city: 'Москва', country: 'Россия' },
  DME: { fullName: 'Москва (Домодедово)', city: 'Москва', country: 'Россия' },
  VKO: { fullName: 'Москва (Внуково)', city: 'Москва', country: 'Россия' },
  LED: { fullName: 'Санкт-Петербург (Пулково)', city: 'Санкт-Петербург', country: 'Россия' },
  UUS: { fullName: 'Южно-Сахалинск (Хомутово)', city: 'Южно-Сахалинск', country: 'Россия' },
  VVO: { fullName: 'Владивосток (Кневичи)', city: 'Владивосток', country: 'Россия' },
  OVB: { fullName: 'Новосибирск (Толмачево)', city: 'Новосибирск', country: 'Россия' },
  KHV: { fullName: 'Хабаровск (Новый)', city: 'Хабаровск', country: 'Россия' },
  IKT: { fullName: 'Иркутск (Байкал)', city: 'Иркутск', country: 'Россия' },
  KJA: { fullName: 'Красноярск (Емельяново)', city: 'Красноярск', country: 'Россия' },
  KUF: { fullName: 'Самара (Курумоч)', city: 'Самара', country: 'Россия' },
  UFA: { fullName: 'Уфа (Мустай Карим)', city: 'Уфа', country: 'Россия' },
  KZN: { fullName: 'Казань (Габдулла Тукай)', city: 'Казань', country: 'Россия' },
  AER: { fullName: 'Сочи (Адлер)', city: 'Сочи', country: 'Россия' },
  SVX: { fullName: 'Екатеринбург (Кольцово)', city: 'Екатеринбург', country: 'Россия' },
  KGD: { fullName: 'Калининград (Храброво)', city: 'Калининград', country: 'Россия' },
  MRV: { fullName: 'Минеральные Воды (КМВ)', city: 'Минеральные Воды', country: 'Россия' },
  TAS: { fullName: 'Ташкент (Ислам Каримов)', city: 'Ташкент', country: 'Узбекистан' },
  ALA: { fullName: 'Алматы (ALA Intl)', city: 'Алматы', country: 'Казахстан' },
  NQZ: { fullName: 'Астана (Нурсултан Назарбаев)', city: 'Астана', country: 'Казахстан' },
  MSQ: { fullName: 'Минск (MSQ-2)', city: 'Минск', country: 'Беларусь' },
  GYD: { fullName: 'Баку (Гейдар Алиев)', city: 'Баку', country: 'Азербайджан' },

  // Asia & Pacific
  DAD: { fullName: 'Дананг (DAD International)', city: 'Дананг', country: 'Вьетнам' },
  CXR: { fullName: 'Нячанг (Камрань)', city: 'Нячанг', country: 'Вьетнам' },
  HAN: { fullName: 'Ханой (Нойбай)', city: 'Ханой', country: 'Вьетнам' },
  SGN: { fullName: 'Хошимин (Таншоннят)', city: 'Хошимин', country: 'Вьетнам' },
  BKK: { fullName: 'Бангкок (Суварнабхуми)', city: 'Бангкок', country: 'Таиланд' },
  DMK: { fullName: 'Бангкок (Донмыанг)', city: 'Бангкок', country: 'Таиланд' },
  HKT: { fullName: 'Пхукет (Международный)', city: 'Пхукет', country: 'Таиланд' },
  DPS: { fullName: 'Бали (Нгурах-Рай)', city: 'Бали', country: 'Индонезия' },
  SIN: { fullName: 'Сингапур (Чанги)', city: 'Сингапур', country: 'Сингапур' },
  KUL: { fullName: 'Куала-Лумпур (KLIA)', city: 'Куала-Лумпур', country: 'Малайзия' },
  PEK: { fullName: 'Пекин (Шоуду)', city: 'Пекин', country: 'Китай' },
  PKX: { fullName: 'Пекин (Дасин)', city: 'Пекин', country: 'Китай' },
  ICN: { fullName: 'Сеул (Инчхон)', city: 'Сеул', country: 'Южная Корея' },
  TYO: { fullName: 'Токио (Нарита/Ханеда)', city: 'Токио', country: 'Япония' },
  NRT: { fullName: 'Токио (Нарита)', city: 'Токио', country: 'Япония' },
  HND: { fullName: 'Токио (Ханеда)', city: 'Токио', country: 'Япония' },

  // Middle East & Europe
  DXB: { fullName: 'Дубай (DXB International)', city: 'Дубай', country: 'ОАЭ' },
  AUH: { fullName: 'Абу-Даби (Зайед Intl)', city: 'Абу-Даби', country: 'ОАЭ' },
  DOH: { fullName: 'Доха (Хамад)', city: 'Доха', country: 'Катар' },
  IST: { fullName: 'Стамбул (Новый аэропорт)', city: 'Стамбул', country: 'Турция' },
  SAW: { fullName: 'Стамбул (Сабиха Гёкчен)', city: 'Стамбул', country: 'Турция' },
  AYT: { fullName: 'Анталья (AYT Intl)', city: 'Анталья', country: 'Турция' },
  PAR: { fullName: 'Париж (Шарль де Голль)', city: 'Париж', country: 'Франция' },
  CDG: { fullName: 'Париж (Шарль де Голль)', city: 'Париж', country: 'Франция' },
  ROM: { fullName: 'Рим (Фьюмичино)', city: 'Рим', country: 'Италия' },
  FCO: { fullName: 'Рим (Фьюмичино)', city: 'Рим', country: 'Италия' },
  LON: { fullName: 'Лондон (Хитроу/Гатвик)', city: 'Лондон', country: 'Великобритания' },
  LHR: { fullName: 'Лондон (Хитроу)', city: 'Лондон', country: 'Великобритания' },
  LGW: { fullName: 'Лондон (Гатвик)', city: 'Лондон', country: 'Великобритания' },
  BER: { fullName: 'Берлин (Бранденбург)', city: 'Берлин', country: 'Германия' },
  MUC: { fullName: 'Мюнхен (Франц Йозеф Штраус)', city: 'Мюнхен', country: 'Германия' },
  FRA: { fullName: 'Франкфурт (Рейн-Майн)', city: 'Франкфурт', country: 'Германия' },
  VIE: { fullName: 'Вена (Швехат)', city: 'Вена', country: 'Австрия' },
  AMS: { fullName: 'Амстердам (Схипхол)', city: 'Амстердам', country: 'Нидерланды' },
  PRG: { fullName: 'Прага (Вацлав Гавел)', city: 'Прага', country: 'Чехия' },
  MAD: { fullName: 'Мадрид (Барахас)', city: 'Мадрид', country: 'Испания' },
  BCN: { fullName: 'Барселона (Эль-Прат)', city: 'Барселона', country: 'Испания' },
  MXP: { fullName: 'Милан (Мальпенса)', city: 'Милан', country: 'Италия' },
  ZRH: { fullName: 'Цюрих (Клотен)', city: 'Цюрих', country: 'Швейцария' },
  EVN: { fullName: 'Ереван (Звартноц)', city: 'Ереван', country: 'Армения' },
  BEG: { fullName: 'Белград (Никола Тесла)', city: 'Белград', country: 'Сербия' },
  BZV: { fullName: 'Браззавиль (Майя-Майя)', city: 'Браззавиль', country: 'Республика Конго' },
  FIH: { fullName: 'Киншаса (Нджили)', city: 'Киншаса', country: 'ДР Конго' },
  ADD: { fullName: 'Аддис-Абеба (Боле)', city: 'Аддис-Абеба', country: 'Эфиопия' },
  PMF: { fullName: 'Парма (Джузеппе Верди)', city: 'Парма', country: 'Италия' },
  CAI: { fullName: 'Каир (Международный)', city: 'Каир', country: 'Египет' },
};

function getAirportInfo(iata: string, cityNameFallback: string): AirportMeta {
  const code = iata.toUpperCase();
  if (AIRPORT_DIRECTORY[code]) {
    return AIRPORT_DIRECTORY[code];
  }
  return {
    fullName: `${cityNameFallback || code} (${code})`,
    city: cityNameFallback || code,
    country: 'Международный',
  };
}

interface TransitHubOption {
  city: string;
  iata: string;
  airline1: string;
  airline1Code: string;
  airline1Flight: string;
  aircraft1: string;
  airline2: string;
  airline2Code: string;
  airline2Flight: string;
  aircraft2: string;
  provider1: string;
  provider2: string;
}

function selectHubs(originIata: string, destIata: string): {
  splitHub: TransitHubOption;
  stpcHub: TransitHubOption;
  fastHub: TransitHubOption;
  directAirline?: { name: string; code: string; flight: string; aircraft: string };
} {
  const o = originIata.toUpperCase();
  const d = destIata.toUpperCase();

  const isFarEast = ['UUS', 'VVO', 'KHV', 'IKT'].includes(o);
  const isSouthEastAsia = ['DAD', 'CXR', 'HAN', 'SGN', 'BKK', 'HKT', 'DPS', 'SIN', 'KUL'].includes(d);
  const isRussia = ['MOW', 'SVO', 'DME', 'VKO', 'LED', 'OVB', 'SVX', 'KZN', 'AER', 'UUS', 'VVO', 'KUF', 'UFA', 'ROV', 'KGD', 'MRV'].includes(o);
  const isEurope = ['LON', 'LHR', 'LGW', 'PAR', 'CDG', 'ROM', 'FCO', 'BER', 'MUC', 'FRA', 'VIE', 'AMS', 'PRG', 'MAD', 'BCN', 'MXP', 'ZRH', 'BEG', 'ATH', 'LIS'].includes(d);
  const isRussiaToEurope = isRussia && isEurope;

  if (isRussiaToEurope || isEurope) {
    return {
      splitHub: {
        city: 'Стамбул',
        iata: 'IST',
        airline1: 'Turkish Airlines',
        airline1Code: 'TK',
        airline1Flight: 'TK 402',
        aircraft1: 'Airbus A330-300',
        airline2: 'Pegasus Airlines',
        airline2Code: 'PC',
        airline2Flight: 'PC 1018',
        aircraft2: 'Airbus A320neo',
        provider1: 'Turkish Airlines Direct',
        provider2: 'Pegasus GDS Direct',
      },
      stpcHub: {
        city: 'Дубай',
        iata: 'DXB',
        airline1: 'Flydubai',
        airline1Code: 'FZ',
        airline1Flight: 'FZ 918',
        aircraft1: 'Boeing 737 MAX 8',
        airline2: 'Emirates',
        airline2Code: 'EK',
        airline2Flight: 'EK 049',
        aircraft2: 'Boeing 777-300ER',
        provider1: 'Flydubai Direct',
        provider2: 'Emirates NDC Direct',
      },
      fastHub: {
        city: 'Ереван',
        iata: 'EVN',
        airline1: 'FlyOne Armenia',
        airline1Code: '3F',
        airline1Flight: '3F 536',
        aircraft1: 'Airbus A320',
        airline2: 'Lufthansa',
        airline2Code: 'LH',
        airline2Flight: 'LH 1455',
        aircraft2: 'Airbus A321neo',
        provider1: 'FlyOne NDC',
        provider2: 'Lufthansa Group Corporate',
      },
      directAirline: undefined, // Strictly NO direct flights from Russia to Europe
    };
  }

  if (isFarEast && isSouthEastAsia) {
    return {
      splitHub: {
        city: 'Ханой',
        iata: 'HAN',
        airline1: 'Vietnam Airlines',
        airline1Code: 'VN',
        airline1Flight: 'VN 534',
        aircraft1: 'Airbus A350-900',
        airline2: 'VietJet Air',
        airline2Code: 'VJ',
        airline2Flight: 'VJ 508',
        aircraft2: 'Airbus A321neo',
        provider1: 'Vietnam Airlines NDC Direct',
        provider2: 'VietJet Air Wholesale GDS',
      },
      stpcHub: {
        city: 'Бангкок',
        iata: 'BKK',
        airline1: 'Thai Airways',
        airline1Code: 'TG',
        airline1Flight: 'TG 924',
        aircraft1: 'Boeing 787-9 Dreamliner',
        airline2: 'Bangkok Airways',
        airline2Code: 'PG',
        airline2Flight: 'PG 947',
        aircraft2: 'Airbus A320',
        provider1: 'Thai Airways Direct',
        provider2: 'Bangkok Airways Fare',
      },
      fastHub: {
        city: 'Пекин',
        iata: 'PEK',
        airline1: 'Air China',
        airline1Code: 'CA',
        airline1Flight: 'CA 182',
        aircraft1: 'Boeing 777-300ER',
        airline2: 'Air China',
        airline2Code: 'CA',
        airline2Flight: 'CA 741',
        aircraft2: 'Airbus A321',
        provider1: 'Air China Global',
        provider2: 'Air China Global',
      },
    };
  }

  // European Russia / Central Russia
  return {
    splitHub: {
      city: 'Доха',
      iata: 'DOH',
      airline1: 'Qatar Airways',
      airline1Code: 'QR',
      airline1Flight: 'QR 338',
      aircraft1: 'Boeing 787-8 Dreamliner',
      airline2: 'VietJet Air',
      airline2Code: 'VJ',
      airline2Flight: 'VJ 862',
      aircraft2: 'Airbus A330-300',
      provider1: 'Qatar Airways NDC Direct',
      provider2: 'VietJet Air Wholesale',
    },
    stpcHub: {
      city: 'Дубай',
      iata: 'DXB',
      airline1: 'Emirates',
      airline1Code: 'EK',
      airline1Flight: 'EK 132',
      aircraft1: 'Airbus A380-800',
      airline2: 'Flydubai',
      airline2Code: 'FZ',
      airline2Flight: 'FZ 571',
      aircraft2: 'Boeing 737 MAX 8',
      provider1: 'Emirates Direct NDC',
      provider2: 'Flydubai Special Agreement',
    },
    fastHub: {
      city: 'Стамбул',
      iata: 'IST',
      airline1: 'Turkish Airlines',
      airline1Code: 'TK',
      airline1Flight: 'TK 414',
      aircraft1: 'Airbus A330-200',
      airline2: 'Turkish Airlines',
      airline2Code: 'TK',
      airline2Flight: 'TK 68',
      aircraft2: 'Boeing 787-9 Dreamliner',
      provider1: 'Turkish Airlines Corporate',
      provider2: 'Turkish Airlines Corporate',
    },
    directAirline: ['MOW', 'LED'].includes(o) && ['DXB', 'IST', 'BKK', 'HKT', 'AER'].includes(d) ? {
      name: 'Аэрофлот',
      code: 'SU',
      flight: 'SU 270',
      aircraft: 'Boeing 777-300ER',
    } : undefined,
  };
}

function toPrepositional(city: string): string {
  const map: Record<string, string> = {
    'Бангкок': 'Бангкоке',
    'Дубай': 'Дубае',
    'Доха': 'Дохе',
    'Ханой': 'Ханое',
    'Стамбул': 'Стамбуле',
    'Сеул': 'Сеуле',
    'Пекин': 'Пекине',
    'Ташкент': 'Ташкенте',
    'Сингапур': 'Сингапуре',
    'Куала-Лумпур': 'Куала-Лумпуре',
    'Токио': 'Токио',
  };
  return map[city] || (city.endsWith('а') ? city.slice(0, -1) + 'е' : city + 'е');
}

export function generateMockFlights(params: ParsedSearchParams): Flight[] {
  const originCity = params.originCity || params.originIata || '';
  const destCity = params.destinationCity || params.destinationIata || '';
  const originIata = params.originIata?.toUpperCase() || '';
  const destIata = params.destinationIata?.toUpperCase() || '';

  if (!originIata || !destIata) {
    return [];
  }

  const originMeta = getAirportInfo(originIata, originCity);
  const destMeta = getAirportInfo(destIata, destCity);

  const departureDate = params.departureDate || '2026-09-14';
  const returnDate = params.returnDate || (params.isOneWay ? undefined : (params.durationDays ? '2026-09-28' : undefined));

  const hasLuggage = params.hasLuggage !== undefined ? params.hasLuggage : (params.baggageIncluded !== undefined ? params.baggageIncluded : true);
  const baggageTag = hasLuggage ? '🧳 Багаж 23 кг' : '🎒 Только ручная кладь';
  const baggageDesc = hasLuggage ? 'Багаж 23 кг + ручная кладь 8 кг' : 'Только ручная кладь 8 кг (без сдаваемого багажа)';

  const passMultiplier = params.passengersCount || 1;
  const classMultiplier = params.cabinClass === 'First' ? 4.0 : params.cabinClass === 'Business' ? 2.6 : params.cabinClass === 'Premium Economy' ? 1.45 : 1;
  const luggageDiff = hasLuggage ? 0 : -3500 * passMultiplier;

  const hubs = selectHubs(originIata, destIata);

  // Price base calculations
  const flight1BasePrice = Math.max(12000, Math.round(44800 * passMultiplier * classMultiplier + luggageDiff));
  const flight1MarketPrice = Math.round(74900 * passMultiplier * classMultiplier);
  const flight1Saved = flight1MarketPrice - flight1BasePrice;

  const flight2BasePrice = Math.max(14000, Math.round(51200 * passMultiplier * classMultiplier + luggageDiff));
  const flight2MarketPrice = Math.round(83500 * passMultiplier * classMultiplier);
  const flight2Saved = flight2MarketPrice - flight2BasePrice;

  const flight3BasePrice = Math.max(13000, Math.round(48900 * passMultiplier * classMultiplier + luggageDiff));
  const flight3MarketPrice = Math.round(76000 * passMultiplier * classMultiplier);
  const flight3Saved = flight3MarketPrice - flight3BasePrice;

  const flight4BasePrice = Math.max(16000, Math.round(62000 * passMultiplier * classMultiplier + luggageDiff));
  const flight4MarketPrice = Math.round(89000 * passMultiplier * classMultiplier);
  const flight4Saved = flight4MarketPrice - flight4BasePrice;

  const splitHubMeta = getAirportInfo(hubs.splitHub.iata, hubs.splitHub.city);
  const stpcHubMeta = getAirportInfo(hubs.stpcHub.iata, hubs.stpcHub.city);
  const fastHubMeta = getAirportInfo(hubs.fastHub.iata, hubs.fastHub.city);

  // Helper to build pricing object
  const createPricing = (basePrice: number, marketPrice: number, reason: string, segment1Title: string, p1: string, segment2Title?: string, p2?: string): PricingBreakdown => {
    const saved = Math.max(0, marketPrice - basePrice);
    const savedPct = Math.min(48, Math.round((saved / marketPrice) * 100));
    const breakdowns: SegmentPriceDetail[] = [
      {
        segmentTitle: segment1Title,
        providerName: p1,
        price: segment2Title ? Math.round(basePrice * 0.58) : basePrice - 1800 * passMultiplier,
        currency: params.currency,
      },
    ];
    if (segment2Title) {
      breakdowns.push({
        segmentTitle: segment2Title,
        providerName: p2 || 'Partner Airline Direct',
        price: Math.round(basePrice * 0.38),
        currency: params.currency,
      });
    }
    breakdowns.push({
      segmentTitle: 'Сервисный сбор & Smart-стыковка',
      providerName: 'FlightSaver Platform',
      price: 1800 * passMultiplier,
      currency: params.currency,
    });

    return {
      currency: params.currency,
      totalPrice: basePrice,
      marketPrice: marketPrice,
      savedAmount: saved,
      savedPercentage: savedPct,
      netSupplierFare: basePrice - 1800 * passMultiplier,
      serviceFee: 1800 * passMultiplier,
      splitSavingsReason: reason,
      segmentBreakdowns: breakdowns,
    };
  };

  const flights: Flight[] = [
    // 1. TOP VALUE SPLIT-TICKET (Morning, 1-stop)
    {
      id: `fl-split-${originIata}-${destIata}-01`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '11ч 20м',
      totalDurationMinutes: 680,
      stopsCount: 1,
      departureTimeOfDay: 'morning',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: true,
      isFastest: false,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: baggageDesc,
      isCorporate: params.isCorporateAccount,
      tags: params.isCorporateAccount 
        ? ['🏢 Корпоративный счет с НДС', '🔥 Топ выгода', 'Раздельная выписка (-40%)', baggageTag]
        : ['🔥 Топ выгода', 'Раздельная выписка (-40%)', baggageTag, 'Гарантия стыковки'],
      transit: {
        hasTransit: true,
        transitCity: hubs.splitHub.city,
        transitAirport: hubs.splitHub.iata,
        transitDuration: '2ч 15м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        flight1BasePrice,
        flight1MarketPrice,
        `Скомбинированы прямые агентские тарифы ${hubs.splitHub.airline1} (${originIata}-${hubs.splitHub.iata}) и ${hubs.splitHub.airline2} (${hubs.splitHub.iata}-${destIata}) без наценок розничных агрегаторов.`,
        `${originCity} (${originIata}) → ${hubs.splitHub.city} (${hubs.splitHub.iata})`,
        hubs.splitHub.provider1,
        `${hubs.splitHub.city} (${hubs.splitHub.iata}) → ${destCity} (${destIata})`,
        hubs.splitHub.provider2
      ),
      segments: [
        {
          airline: hubs.splitHub.airline1,
          airlineCode: hubs.splitHub.airline1Code,
          flightNumber: hubs.splitHub.airline1Flight,
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: hubs.splitHub.city,
          toAirport: splitHubMeta.fullName,
          toIata: hubs.splitHub.iata,
          departureTime: '08:40',
          arrivalTime: '14:25',
          duration: '5ч 45м',
          bookingProvider: hubs.splitHub.provider1,
          cabinClass: params.cabinClass || 'Economy',
          aircraft: hubs.splitHub.aircraft1,
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: hubs.splitHub.airline2,
          airlineCode: hubs.splitHub.airline2Code,
          flightNumber: hubs.splitHub.airline2Flight,
          fromCity: hubs.splitHub.city,
          fromAirport: splitHubMeta.fullName,
          toCity: destCity,
          toAirport: destMeta.fullName,
          fromIata: hubs.splitHub.iata,
          toIata: destIata,
          departureTime: '16:40',
          arrivalTime: '20:00',
          duration: '3ч 20м',
          bookingProvider: hubs.splitHub.provider2,
          cabinClass: params.cabinClass || 'Economy',
          aircraft: hubs.splitHub.aircraft2,
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 2. FASTEST ROUTE (Day, 1-stop)
    {
      id: `fl-fast-${originIata}-${destIata}-02`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '9ч 50м',
      totalDurationMinutes: 590,
      stopsCount: 1,
      departureTimeOfDay: 'day',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: false,
      isFastest: true,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: hasLuggage ? 'Багаж 23 кг + ручная кладь 10 кг' : 'Только ручная кладь 10 кг',
      isCorporate: params.isCorporateAccount,
      tags: params.isCorporateAccount 
        ? ['🏢 Корпоративный счет', '⚡ Самый быстрый', baggageTag]
        : ['⚡ Самый быстрый', baggageTag, 'Единый PNR'],
      transit: {
        hasTransit: true,
        transitCity: hubs.fastHub.city,
        transitAirport: hubs.fastHub.iata,
        transitDuration: '1ч 35м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        flight3BasePrice,
        flight3MarketPrice,
        `Оптимизированный единый сквозной маршрут ${hubs.fastHub.airline1} с экспресс-стыковкой в ${hubs.fastHub.city}.`,
        `${originCity} (${originIata}) → ${destCity} (${destIata})`,
        `${hubs.fastHub.airline1} Through Fare`
      ),
      segments: [
        {
          airline: hubs.fastHub.airline1,
          airlineCode: hubs.fastHub.airline1Code,
          flightNumber: hubs.fastHub.airline1Flight,
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: hubs.fastHub.city,
          toAirport: fastHubMeta.fullName,
          toIata: hubs.fastHub.iata,
          departureTime: '13:00',
          arrivalTime: '17:45',
          duration: '4ч 45м',
          bookingProvider: hubs.fastHub.provider1,
          cabinClass: params.cabinClass || 'Economy',
          aircraft: hubs.fastHub.aircraft1,
          baggage: hasLuggage ? '23 кг сдаваемый' : '10 кг ручная кладь',
        },
        {
          airline: hubs.fastHub.airline2,
          airlineCode: hubs.fastHub.airline2Code,
          flightNumber: hubs.fastHub.airline2Flight,
          fromCity: hubs.fastHub.city,
          fromAirport: fastHubMeta.fullName,
          fromIata: hubs.fastHub.iata,
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '19:20',
          arrivalTime: '22:50',
          duration: '3ч 30м',
          bookingProvider: hubs.fastHub.provider2,
          cabinClass: params.cabinClass || 'Economy',
          aircraft: hubs.fastHub.aircraft2,
          baggage: hasLuggage ? '23 кг сдаваемый' : '10 кг ручная кладь',
        },
      ],
    },

    // 3. FREE STPC 4★ TRANSIT HOTEL (Day, 1-stop with STPC)
    {
      id: `fl-stpc-${originIata}-${destIata}-03`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '18ч 30м',
      totalDurationMinutes: 1110,
      stopsCount: 1,
      departureTimeOfDay: 'day',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: false,
      isFastest: false,
      isStpcEligible: true,
      baggageIncluded: hasLuggage,
      baggageDescription: hasLuggage ? 'Багаж 30 кг + отель STPC 4★ с трансфером и завтраком' : 'Только ручная кладь 8 кг + отель STPC 4★',
      isCorporate: params.isCorporateAccount,
      tags: params.isCorporateAccount 
        ? ['🏢 Корпоративный счет', '🏨 Отель STPC 4★ Бесплатно', 'Комфортный отдых', baggageTag]
        : ['🏨 Отель STPC 4★ Бесплатно', 'Комфортный отдых', baggageTag, 'Питание включено'],
      transit: {
        hasTransit: true,
        transitCity: hubs.stpcHub.city,
        transitAirport: hubs.stpcHub.iata,
        transitDuration: '10ч 45м (Дневной отдых)',
        stpcHotelIncluded: true,
        stpcDetails: `Бесплатный 4★ отель в ${toPrepositional(hubs.stpcHub.city)} (Novotel Airport / Millennium) с трансфером из терминала и горячим питанием`,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        flight2BasePrice,
        flight2MarketPrice,
        `Тариф включает официальный транзитный ваучер авиакомпании ${hubs.stpcHub.airline1} на бесплатный 4★ отель и трансфер.`,
        `${originCity} (${originIata}) → ${hubs.stpcHub.city} (${hubs.stpcHub.iata})`,
        hubs.stpcHub.provider1,
        `${hubs.stpcHub.city} (${hubs.stpcHub.iata}) → ${destCity} (${destIata})`,
        hubs.stpcHub.provider2
      ),
      segments: [
        {
          airline: hubs.stpcHub.airline1,
          airlineCode: hubs.stpcHub.airline1Code,
          flightNumber: hubs.stpcHub.airline1Flight,
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: hubs.stpcHub.city,
          toAirport: stpcHubMeta.fullName,
          toIata: hubs.stpcHub.iata,
          departureTime: '11:15',
          arrivalTime: '17:30',
          duration: '6ч 15м',
          bookingProvider: hubs.stpcHub.provider1,
          cabinClass: params.cabinClass || 'Economy',
          aircraft: hubs.stpcHub.aircraft1,
          baggage: hasLuggage ? '30 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: hubs.stpcHub.airline2,
          airlineCode: hubs.stpcHub.airline2Code,
          flightNumber: hubs.stpcHub.airline2Flight,
          fromCity: hubs.stpcHub.city,
          fromAirport: stpcHubMeta.fullName,
          fromIata: hubs.stpcHub.iata,
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '04:15',
          arrivalTime: '08:45',
          duration: '4ч 30м',
          bookingProvider: hubs.stpcHub.provider2,
          cabinClass: params.cabinClass || 'Economy',
          aircraft: hubs.stpcHub.aircraft2,
          baggage: hasLuggage ? '30 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 4. EVENING EXPRESS VIA ISTANBUL (Evening, 1-stop)
    {
      id: `fl-prem-${originIata}-${destIata}-04`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '8ч 30м',
      totalDurationMinutes: 510,
      stopsCount: 1,
      departureTimeOfDay: 'evening',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: false,
      isFastest: true,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: hasLuggage ? 'Багаж 23 кг + ручная кладь 8 кг' : 'Только ручная кладь 8 кг',
      isCorporate: params.isCorporateAccount,
      tags: params.isCorporateAccount
        ? ['🏢 Корпоративный счет с НДС', '⚡ Вечерний Split-рейс', 'Стамбул SAW', baggageTag]
        : ['⚡ Вечерний Split-рейс', 'Стамбул SAW', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Стамбул',
        transitAirport: 'SAW',
        transitDuration: '1ч 45м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        flight4BasePrice,
        flight4MarketPrice,
        'Сплит-маршрут Pegasus Airlines через Стамбул (SAW) без необходимости транзитной визы.',
        `${originCity} (${originIata}) → Стамбул (SAW)`,
        'Pegasus Direct',
        `Стамбул (SAW) → ${destCity} (${destIata})`,
        'Pegasus Direct'
      ),
      segments: [
        {
          airline: 'Pegasus Airlines',
          airlineCode: 'PC',
          flightNumber: 'PC 397',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Стамбул',
          toAirport: 'Стамбул (Сабиха Гёкчен)',
          toIata: 'SAW',
          departureTime: '18:20',
          arrivalTime: '22:50',
          duration: '4ч 30м',
          bookingProvider: 'Pegasus Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A320neo',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: 'Pegasus Airlines',
          airlineCode: 'PC',
          flightNumber: 'PC 1022',
          fromCity: 'Стамбул',
          fromAirport: 'Стамбул (Сабиха Гёкчен)',
          fromIata: 'SAW',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '00:35',
          arrivalTime: '02:50',
          duration: '2ч 15м',
          bookingProvider: 'Pegasus Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A320neo',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 5. SUPER-SAVER NIGHT SPLIT (Night, 1-stop)
    {
      id: `fl-saver-${originIata}-${destIata}-05`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '12ч 45м',
      totalDurationMinutes: 765,
      stopsCount: 1,
      departureTimeOfDay: 'night',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: true,
      isFastest: false,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: baggageDesc,
      isCorporate: params.isCorporateAccount,
      tags: ['🔥 Супер-эконом', 'Ночной вылет', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Баку',
        transitAirport: 'GYD',
        transitDuration: '2ч 40м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight1BasePrice * 0.92),
        Math.round(flight1MarketPrice * 0.95),
        'Экономичный ночной транзит через Международный аэропорт Гейдар Алиев (GYD).',
        `${originCity} (${originIata}) → Баку (GYD)`,
        'AZAL Direct NDC',
        `Баку (GYD) → ${destCity} (${destIata})`,
        'Wizz Air Wholesale'
      ),
      segments: [
        {
          airline: 'Azerbaijan Airlines',
          airlineCode: 'J2',
          flightNumber: 'J2 808',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Баку',
          toAirport: 'Баку (Гейдар Алиев)',
          toIata: 'GYD',
          departureTime: '01:25',
          arrivalTime: '05:30',
          duration: '4ч 05м',
          bookingProvider: 'AZAL API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A320neo',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: 'British Airways',
          airlineCode: 'BA',
          flightNumber: 'BA 144',
          fromCity: 'Баку',
          fromAirport: 'Баку (Гейдар Алиев)',
          fromIata: 'GYD',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '08:10',
          arrivalTime: '14:10',
          duration: '6ч 00м',
          bookingProvider: 'British Airways Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 777-200',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 6. AFTERNOON EXPRESS (Day, 1-stop)
    {
      id: `fl-aft-${originIata}-${destIata}-06`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '9ч 10м',
      totalDurationMinutes: 550,
      stopsCount: 1,
      departureTimeOfDay: 'day',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: false,
      isFastest: true,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: baggageDesc,
      isCorporate: params.isCorporateAccount,
      tags: ['⚡ Быстрая стыковка', 'Дневной вылет', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Абу-Даби',
        transitAirport: 'AUH',
        transitDuration: '1ч 45м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight3BasePrice * 1.05),
        flight3MarketPrice,
        'Сквозной дневной маршрут Etihad Airways через хаб в Абу-Даби (AUH).',
        `${originCity} (${originIata}) → ${destCity} (${destIata})`,
        'Etihad Airways NDC'
      ),
      segments: [
        {
          airline: 'Etihad Airways',
          airlineCode: 'EY',
          flightNumber: 'EY 842',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Абу-Даби',
          toAirport: 'Абу-Даби (Зайед)',
          toIata: 'AUH',
          departureTime: '13:40',
          arrivalTime: '19:15',
          duration: '5ч 35м',
          bookingProvider: 'Etihad API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 787-10',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: 'Etihad Airways',
          airlineCode: 'EY',
          flightNumber: 'EY 19',
          fromCity: 'Абу-Даби',
          fromAirport: 'Абу-Даби (Зайед)',
          fromIata: 'AUH',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '21:00',
          arrivalTime: '22:50',
          duration: '3ч 50м',
          bookingProvider: 'Etihad API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A350-1000',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 7. STPC NIGHT REST 4★ (Evening, 1-stop with STPC)
    {
      id: `fl-stpc-night-${originIata}-${destIata}-07`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '19ч 40м',
      totalDurationMinutes: 1180,
      stopsCount: 1,
      departureTimeOfDay: 'evening',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: false,
      isFastest: false,
      isStpcEligible: true,
      baggageIncluded: hasLuggage,
      baggageDescription: hasLuggage ? 'Багаж 30 кг + отель STPC 4★' : 'Только ручная кладь + отель STPC 4★',
      isCorporate: params.isCorporateAccount,
      tags: ['🏨 Отель STPC 4★ Бесплатно', 'Ночной сон в отеле', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Доха',
        transitAirport: 'DOH',
        transitDuration: '11ч 15м (Ночной сон в отеле)',
        stpcHotelIncluded: true,
        stpcDetails: 'Бесплатный 4★ отель Oryx Airport Hotel с трансфером и завтраком в Дохе',
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight2BasePrice * 1.02),
        flight2MarketPrice,
        'Официальная программа Qatar Airways Transit Accommodation (STPC).',
        `${originCity} (${originIata}) → Доха (DOH)`,
        'Qatar Airways Direct',
        `Доха (DOH) → ${destCity} (${destIata})`,
        'Qatar Airways Direct'
      ),
      segments: [
        {
          airline: 'Qatar Airways',
          airlineCode: 'QR',
          flightNumber: 'QR 334',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Доха',
          toAirport: 'Доха (Хамад)',
          toIata: 'DOH',
          departureTime: '20:50',
          arrivalTime: '01:45',
          duration: '4ч 55м',
          bookingProvider: 'Qatar Airways',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A350-900',
          baggage: hasLuggage ? '30 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: 'Qatar Airways',
          airlineCode: 'QR',
          flightNumber: 'QR 7',
          fromCity: 'Доха',
          fromAirport: 'Доха (Хамад)',
          fromIata: 'DOH',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '13:00',
          arrivalTime: '16:30',
          duration: '6ч 30м',
          bookingProvider: 'Qatar Airways',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 777-300ER',
          baggage: hasLuggage ? '30 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 8. SMART MORNING FLIGHT (Morning, 1-stop)
    {
      id: `fl-morn-${originIata}-${destIata}-08`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '10ч 20м',
      totalDurationMinutes: 620,
      stopsCount: 1,
      departureTimeOfDay: 'morning',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: true,
      isFastest: false,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: baggageDesc,
      isCorporate: params.isCorporateAccount,
      tags: ['🌅 Ранний вылет', 'Удобное время', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Ташкент',
        transitAirport: 'TAS',
        transitDuration: '2ч 05м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight1BasePrice * 0.96),
        flight1MarketPrice,
        'Тариф с оптимизированной стыковкой через Международный аэропорт Ташкент (TAS).',
        `${originCity} (${originIata}) → Ташкент (TAS)`,
        'Uzbekistan Airways Direct',
        `Ташкент (TAS) → ${destCity} (${destIata})`,
        'Uzbekistan Airways Direct'
      ),
      segments: [
        {
          airline: 'Uzbekistan Airways',
          airlineCode: 'HY',
          flightNumber: 'HY 604',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Ташкент',
          toAirport: 'Ташкент (Ислам Каримов)',
          toIata: 'TAS',
          departureTime: '06:40',
          arrivalTime: '11:55',
          duration: '4ч 15м',
          bookingProvider: 'Uzbekistan Airways API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 787-8',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: 'Uzbekistan Airways',
          airlineCode: 'HY',
          flightNumber: 'HY 201',
          fromCity: 'Ташкент',
          fromAirport: 'Ташкент (Ислам Каримов)',
          fromIata: 'TAS',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '14:00',
          arrivalTime: '17:00',
          duration: '6ч 00м',
          bookingProvider: 'Uzbekistan Airways API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 787-8',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 9. COMFORT BUSINESS / PREMIUM (Morning, 1-stop)
    {
      id: `fl-biz-${originIata}-${destIata}-09`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '9ч 10м',
      totalDurationMinutes: 550,
      stopsCount: 1,
      departureTimeOfDay: 'morning',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: false,
      isFastest: true,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: hasLuggage ? 'Багаж 2 места по 32 кг + Lounge доступ' : 'Ручная кладь + Lounge доступ',
      isCorporate: true,
      tags: ['🏢 Бизнес комфорт', 'Lounge доступ', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Дубай',
        transitAirport: 'DXB',
        transitDuration: '1ч 40м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight4BasePrice * 1.15),
        Math.round(flight4MarketPrice * 1.2),
        'Премиальный корпоративный тариф с гибкими условиями отмены и доступом в Business Lounge.',
        `${originCity} (${originIata}) → ${destCity} (${destIata})`,
        'Emirates Business Direct'
      ),
      segments: [
        {
          airline: 'Emirates',
          airlineCode: 'EK',
          flightNumber: 'EK 130',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Дубай',
          toAirport: 'Дубай (DXB)',
          toIata: 'DXB',
          departureTime: '10:10',
          arrivalTime: '15:45',
          duration: '5ч 35м',
          bookingProvider: 'Emirates API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A380-800',
          baggage: hasLuggage ? '32 кг сдаваемый' : '10 кг ручная кладь',
        },
        {
          airline: 'Emirates',
          airlineCode: 'EK',
          flightNumber: 'EK 03',
          fromCity: 'Дубай',
          fromAirport: 'Дубай (DXB)',
          fromIata: 'DXB',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '17:25',
          arrivalTime: '19:20',
          duration: '3ч 55м',
          bookingProvider: 'Emirates API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A380-800',
          baggage: hasLuggage ? '32 кг сдаваемый' : '10 кг ручная кладь',
        },
      ],
    },

    // 10. SPLIT-TICKET VIA GULF (Day, 1-stop)
    {
      id: `fl-gulf-${originIata}-${destIata}-10`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '12ч 40м',
      totalDurationMinutes: 760,
      stopsCount: 1,
      departureTimeOfDay: 'day',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: true,
      isFastest: false,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: baggageDesc,
      isCorporate: params.isCorporateAccount,
      tags: ['🔥 Выгодный Split', 'Бахрейн хаб', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Манама',
        transitAirport: 'BAH',
        transitDuration: '2ч 50м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight1BasePrice * 0.94),
        flight1MarketPrice,
        'Сплит-выписка через Gulf Air с гарантированной пересадкой в Манаме (BAH).',
        `${originCity} (${originIata}) → Манама (BAH)`,
        'Gulf Air API',
        `Манама (BAH) → ${destCity} (${destIata})`,
        'Gulf Air API'
      ),
      segments: [
        {
          airline: 'Gulf Air',
          airlineCode: 'GF',
          flightNumber: 'GF 015',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Манама',
          toAirport: 'Бахрейн (BAH)',
          toIata: 'BAH',
          departureTime: '15:30',
          arrivalTime: '20:50',
          duration: '5ч 20м',
          bookingProvider: 'Gulf Air API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 787-9',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: 'Gulf Air',
          airlineCode: 'GF',
          flightNumber: 'GF 003',
          fromCity: 'Манама',
          fromAirport: 'Бахрейн (BAH)',
          fromIata: 'BAH',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '23:40',
          arrivalTime: '04:10',
          duration: '6ч 30м',
          bookingProvider: 'Gulf Air API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 787-9',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 11. BUDGET 2-STOP SAVER (Day, 2-stops)
    {
      id: `fl-2stop-${originIata}-${destIata}-11`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '17ч 00м',
      totalDurationMinutes: 1020,
      stopsCount: 2,
      departureTimeOfDay: 'day',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: true,
      isFastest: false,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: baggageDesc,
      isCorporate: params.isCorporateAccount,
      tags: ['💰 Максимальная экономия (-48%)', '2 пересадки', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Ереван / Стамбул',
        transitAirport: 'EVN / SAW',
        transitDuration: '1ч 45м + 2ч 10м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight1BasePrice * 0.78),
        flight1MarketPrice,
        'Максимальная раздельная оптимизация по трем стыковочным сегментам.',
        `${originCity} (${originIata}) → Ереван (EVN)`,
        'FlyOne Armenia Direct',
        `Стамбул (SAW) → ${destCity} (${destIata})`,
        'Pegasus Airlines Wholesale'
      ),
      segments: [
        {
          airline: 'FlyOne Armenia',
          airlineCode: '3F',
          flightNumber: '3F 542',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Ереван',
          toAirport: 'Ереван (Звартноц)',
          toIata: 'EVN',
          departureTime: '14:15',
          arrivalTime: '18:10',
          duration: '3ч 55м',
          bookingProvider: 'FlyOne Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A320',
          baggage: hasLuggage ? '20 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: 'Pegasus Airlines',
          airlineCode: 'PC',
          flightNumber: 'PC 1161',
          fromCity: 'Стамбул',
          fromAirport: 'Стамбул (Сабиха Гёкчен)',
          fromIata: 'SAW',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '23:30',
          arrivalTime: '07:15',
          duration: '5ч 45м',
          bookingProvider: 'Pegasus Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A321neo',
          baggage: hasLuggage ? '20 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 12. EARLY BIRD EXPRESS (Morning, 1-stop)
    {
      id: `fl-early-${originIata}-${destIata}-12`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '8ч 15м',
      totalDurationMinutes: 495,
      stopsCount: 1,
      departureTimeOfDay: 'morning',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: false,
      isFastest: true,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: baggageDesc,
      isCorporate: params.isCorporateAccount,
      tags: ['⚡ Утренний экспресс', 'Быстрая пересадка', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Анкара',
        transitAirport: 'ESB',
        transitDuration: '1ч 20м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight3BasePrice * 0.98),
        flight3MarketPrice,
        'Утренний транзитный рейс Turkish Airlines с быстрой стыковкой в Анкаре.',
        `${originCity} (${originIata}) → ${destCity} (${destIata})`,
        'Turkish Airlines Corporate'
      ),
      segments: [
        {
          airline: 'Turkish Airlines',
          airlineCode: 'TK',
          flightNumber: 'TK 312',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Анкара',
          toAirport: 'Анкара (Эсенбога)',
          toIata: 'ESB',
          departureTime: '06:10',
          arrivalTime: '09:40',
          duration: '3ч 30м',
          bookingProvider: 'Turkish Airlines Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 737-800',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: 'Turkish Airlines',
          airlineCode: 'TK',
          flightNumber: 'TK 1983',
          fromCity: 'Анкара',
          fromAirport: 'Анкара (Эсенбога)',
          fromIata: 'ESB',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '11:00',
          arrivalTime: '14:25',
          duration: '3ч 25м',
          bookingProvider: 'Turkish Airlines Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A321neo',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 13. SUNSET EXPRESS (Evening, 1-stop)
    {
      id: `fl-sunset-${originIata}-${destIata}-13`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '9ч 20м',
      totalDurationMinutes: 560,
      stopsCount: 1,
      departureTimeOfDay: 'evening',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: false,
      isFastest: true,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: baggageDesc,
      isCorporate: params.isCorporateAccount,
      tags: ['🌅 Вечерний экспресс', 'Комфортные стыковки', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Шарджа',
        transitAirport: 'SHJ',
        transitDuration: '1ч 50м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight1BasePrice * 1.02),
        flight1MarketPrice,
        'Эффективный вечерний маршрут Air Arabia через Шарджу (SHJ).',
        `${originCity} (${originIata}) → ${destCity} (${destIata})`,
        'Air Arabia Direct'
      ),
      segments: [
        {
          airline: 'Air Arabia',
          airlineCode: 'G9',
          flightNumber: 'G9 956',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Шарджа',
          toAirport: 'Шарджа (SHJ)',
          toIata: 'SHJ',
          departureTime: '17:50',
          arrivalTime: '23:30',
          duration: '5ч 40м',
          bookingProvider: 'Air Arabia Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A321LR',
          baggage: hasLuggage ? '20 кг сдаваемый' : '10 кг ручная кладь',
        },
        {
          airline: 'Air Arabia',
          airlineCode: 'G9',
          flightNumber: 'G9 102',
          fromCity: 'Шарджа',
          fromAirport: 'Шарджа (SHJ)',
          fromIata: 'SHJ',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '01:20',
          arrivalTime: '03:10',
          duration: '3ч 50м',
          bookingProvider: 'Air Arabia Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A321LR',
          baggage: hasLuggage ? '20 кг сдаваемый' : '10 кг ручная кладь',
        },
      ],
    },

    // 14. TURKISH AIRLINES STPC 4★ (Day, 1-stop with STPC)
    {
      id: `fl-stpc-ist-${originIata}-${destIata}-14`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '19ч 30м',
      totalDurationMinutes: 1170,
      stopsCount: 1,
      departureTimeOfDay: 'day',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: false,
      isFastest: false,
      isStpcEligible: true,
      baggageIncluded: hasLuggage,
      baggageDescription: hasLuggage ? 'Багаж 30 кг + отель STPC 4★ в Стамбуле' : 'Ручная кладь + отель STPC 4★',
      isCorporate: params.isCorporateAccount,
      tags: ['🏨 Отель STPC 4★ Бесплатно', 'Тур по Стамбулу', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Стамбул',
        transitAirport: 'IST',
        transitDuration: '12ч 00м (Отель + тур по городу)',
        stpcHotelIncluded: true,
        stpcDetails: 'Бесплатный 4★ отель Turkish Airlines Stopover Istanbul в историческом центре с трансфером',
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight2BasePrice * 1.04),
        flight2MarketPrice,
        'Программа Turkish Airlines Stopover Service с бесплатным 4★ отелем в Стамбуле.',
        `${originCity} (${originIata}) → Стамбул (IST)`,
        'Turkish Airlines Direct',
        `Стамбул (IST) → ${destCity} (${destIata})`,
        'Turkish Airlines Direct'
      ),
      segments: [
        {
          airline: 'Turkish Airlines',
          airlineCode: 'TK',
          flightNumber: 'TK 416',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Стамбул',
          toAirport: 'Стамбул (IST)',
          toIata: 'IST',
          departureTime: '12:45',
          arrivalTime: '17:15',
          duration: '4ч 30м',
          bookingProvider: 'Turkish Airlines Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A330-300',
          baggage: hasLuggage ? '30 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: 'Turkish Airlines',
          airlineCode: 'TK',
          flightNumber: 'TK 1971',
          fromCity: 'Стамбул',
          fromAirport: 'Стамбул (IST)',
          fromIata: 'IST',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '05:15',
          arrivalTime: '08:15',
          duration: '4ч 00м',
          bookingProvider: 'Turkish Airlines Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 777-300ER',
          baggage: hasLuggage ? '30 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 15. EVENING SPLIT-FARE (Evening, 1-stop)
    {
      id: `fl-eve-split-${originIata}-${destIata}-15`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '12ч 50м',
      totalDurationMinutes: 770,
      stopsCount: 1,
      departureTimeOfDay: 'evening',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: true,
      isFastest: false,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: baggageDesc,
      isCorporate: params.isCorporateAccount,
      tags: ['🔥 Выгодный Split', 'Вечерний вылет', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Кувейт',
        transitAirport: 'KWI',
        transitDuration: '3ч 10м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight1BasePrice * 0.95),
        flight1MarketPrice,
        'Оптимизированная раздельная выписка через Международный аэропорт Кувейт (KWI).',
        `${originCity} (${originIata}) → Кувейт (KWI)`,
        'Kuwait Airways Direct',
        `Кувейт (KWI) → ${destCity} (${destIata})`,
        'Kuwait Airways Direct'
      ),
      segments: [
        {
          airline: 'Kuwait Airways',
          airlineCode: 'KU',
          flightNumber: 'KU 132',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Кувейт',
          toAirport: 'Кувейт (KWI)',
          toIata: 'KWI',
          departureTime: '19:40',
          arrivalTime: '00:50',
          duration: '5ч 10м',
          bookingProvider: 'Kuwait Airways API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Airbus A330-800neo',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
        {
          airline: 'Kuwait Airways',
          airlineCode: 'KU',
          flightNumber: 'KU 101',
          fromCity: 'Кувейт',
          fromAirport: 'Кувейт (KWI)',
          fromIata: 'KWI',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '04:00',
          arrivalTime: '08:30',
          duration: '6ч 30м',
          bookingProvider: 'Kuwait Airways API',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 777-300ER',
          baggage: hasLuggage ? '23 кг сдаваемый' : '8 кг ручная кладь',
        },
      ],
    },

    // 16. NIGHT FLYDUBAI VALUE (Night, 1-stop)
    {
      id: `fl-night-fly-${originIata}-${destIata}-16`,
      originCity,
      destinationCity: destCity,
      originIata,
      destinationIata: destIata,
      departureDate,
      returnDate,
      totalDuration: '11ч 50м',
      totalDurationMinutes: 710,
      stopsCount: 1,
      departureTimeOfDay: 'night',
      passengersCount: passMultiplier,
      cabinClass: params.cabinClass || 'Economy',
      isBestValue: true,
      isFastest: false,
      isStpcEligible: false,
      baggageIncluded: hasLuggage,
      baggageDescription: baggageDesc,
      isCorporate: params.isCorporateAccount,
      tags: ['🔥 Ночной Smart-тариф', 'Дубай T2/T3', baggageTag],
      transit: {
        hasTransit: true,
        transitCity: 'Дубай',
        transitAirport: 'DXB',
        transitDuration: '2ч 30м',
        stpcHotelIncluded: false,
        visaFreeTransit: true,
        baggageRecheckRequired: false,
      },
      pricing: createPricing(
        Math.round(flight1BasePrice * 0.93),
        flight1MarketPrice,
        'Ночной стыковочный рейс Flydubai & Emirates через терминал 2/3 Дубая.',
        `${originCity} (${originIata}) → Дубай (DXB)`,
        'Flydubai Direct',
        `Дубай (DXB) → ${destCity} (${destIata})`,
        'Emirates Direct'
      ),
      segments: [
        {
          airline: 'Flydubai',
          airlineCode: 'FZ',
          flightNumber: 'FZ 968',
          fromCity: originCity,
          fromAirport: originMeta.fullName,
          fromIata: originIata,
          toCity: 'Дубай',
          toAirport: 'Дубай (DXB)',
          toIata: 'DXB',
          departureTime: '23:10',
          arrivalTime: '05:00',
          duration: '5ч 50м',
          bookingProvider: 'Flydubai Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 737 MAX 8',
          baggage: hasLuggage ? '20 кг сдаваемый' : '7 кг ручная кладь',
        },
        {
          airline: 'Emirates',
          airlineCode: 'EK',
          flightNumber: 'EK 029',
          fromCity: 'Дубай',
          fromAirport: 'Дубай (DXB)',
          fromIata: 'DXB',
          toCity: destCity,
          toAirport: destMeta.fullName,
          toIata: destIata,
          departureTime: '07:30',
          arrivalTime: '11:00',
          duration: '4ч 30м',
          bookingProvider: 'Emirates Direct',
          cabinClass: params.cabinClass || 'Economy',
          aircraft: 'Boeing 777-300ER',
          baggage: hasLuggage ? '20 кг сдаваемый' : '7 кг ручная кладь',
        },
      ],
    },
  ];

  return flights;
}
